### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by AlexNT1** [Gameboypi/SPW#18]

**Comment by AlexNT1** [comment]
Hi,
I have question.How are pi and PCB connected?
It looks like soldering the pi's GPIO part and pcb.
Is this all right in this way of thinking.

Thank you for reading this question.and I'm glad to answer this question.

**Comment by BRaSSaS** [comment]
Yes, everything is designed to be welded on the main PCB, it is designed so that the welding holes / pads coincide on the 2 plates. This is true for everything, for the PRI board, the sound board and the battery charging plate.
Anyway, you can see the assembly process on this git, it's very well illustrated.

**Comment by Gameboypi** [comment]
Thank you BRaSSaS! :D

**Comment by AlexNT1** [comment]
Thank you for answering　BRaSSaS!
and thank you for leading this question Gameboypi!

It is my first time to do electronic work, but I will challenge while enjoying it

**Comment by Gameboypi** [comment]
Good luck dude!
